### ISSUE TITLE
Use server.broadcastMessage(...)

### ISSUE THREAD

**Issue by boformer** [CraftIRC/4Sponge#1]
You can replace

```
this.plugin.getGame().getServer().get().getOnlinePlayers().forEach(player -> player.sendMessage(message);
```

with

```
this.plugin.getGame().getServer().broadcastMessage(message);
```

in the `MinecraftEndpoint` class.

**Comment by mbax** [comment]
Thanks for looking at it, but see the section above it. Once the new chat handling system comes into play, with the ability to direct who is receiving a message, that line you quoted won't be used. :)
