### ISSUE TITLE
SENDER_NAME does not appear to be implemented for joins and quits

### ISSUE THREAD

**Issue by helkarakse** [CraftIRC/4Sponge#3]
Hi there, I've configured my joins and quits to use the %SENDER_NAME% token as part of the datamapper filter message, but it's replacing it with blank. I don't have the configuration on hand atm, but it's something like:

message: "[%SENDER_NAME% disconnected]", which produces "[ disconnected]" as a result.

In addition, is there a way, or a setting, for the IRC -> Minecraft mirror to strip the \u000f (I think it is this one) character before producing it in Minecraft? Currently, it causes a large square block to appear in chat; I suspect that Minecraft has no idea how to render the unicode character. If you rather have this one on a separate issue, please let me know.

**Comment by mbax** [comment]
In 4.0.9
https://github.com/CraftIRC/4Sponge/commit/4f0e00765a3bed89891b29e12bb42615a08e394c
