### ISSUE TITLE
Version update, like everytime?

### ISSUE THREAD

**Issue by keanucz** [CraftIRC/4Sponge#6]
I updated to 4.1.3, but.. uhm..
It says there's a new version available?
[14:19:32] [pool-2-thread-8/INFO] [craftirc/luckperms]: New version available: 4.1.3-for-5.0.0
Just for reference. 💯 
(also sorry, kitteh..)

**Comment by Hund** [comment]
I have the same issue. Kinda annoying. :)

**Comment by mbax** [comment]
I'm going to go ahead and resolve this by, for now, removing update checking. I'll reintroduce it when Ore is live, using Ore to check for updates.

Expect 4.1.4 shortly.
